# Generated by Django 3.2 on 2023-01-17 12:32

import article.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('Board_id', models.AutoField(primary_key=True, serialize=False)),
                ('Board_share', models.CharField(choices=[('희망', '희망'), ('비희망', '비희망')], default='희망', max_length=100)),
                ('Board_gtype', models.CharField(max_length=100)),
                ('Board_title', models.CharField(max_length=250)),
                ('Board_content', models.TextField()),
                ('Board_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('Board_writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Board_image', models.ImageField(upload_to=article.models.user_directory_path)),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postimage', to='article.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment_content', models.CharField(max_length=200)),
                ('Comment_datetime', models.DateTimeField(auto_now=True)),
                ('Comment_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.post')),
                ('Comment_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
