# Generated by Django 3.2 on 2023-01-17 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_hp', models.ImageField(upload_to='goods/image/')),
                ('design_gr', models.ImageField(upload_to='goods/image/')),
                ('design_kr', models.ImageField(upload_to='goods/image/')),
                ('design_ts', models.ImageField(upload_to='goods/image/')),
                ('design_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
